version: "3"
services:
  php:
    build:
        context: .
        dockerfile: ./docker/php/Dockerfile
    volumes:
      - "./html:/var/www/html"
    ports:
      - "${PHP_PORT}:8000"
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./docker/nginx/conf.d:/etc/nginx/conf.d"
    ports:
      - "${NGINX_PORT}:80"
